use num_enum::TryFromPrimitive;

#[repr(u8)]
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum PowerStatus {
    On = 0,
    Standby = 1,
    InTransitionStandbyToOn = 2,
    InTransitionOnToStandby = 3,
    Unknown = 153,
}

#[repr(u8)]
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum AbortReason {
    UnrecognisedOpcode = 0,
    WrongMode = 1,
    CannotProvideSource = 2,
    InvalidOperand = 3,
    Refused = 4,
    Undetermined = 5,
}

#[repr(u8)]
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum Opcode {
    FeatureAbort = 0x00,
    ImageViewOn = 0x04,
    TunerStepIncrement = 0x05,
    TunerStepDecrement = 0x06,
    TunerDeviceStatus = 0x07,
    GiveTunerDeviceStatus = 0x08,
    RecordOn = 0x09,
    RecordStatus = 0x0A,
    RecordOff = 0x0B,
    TextViewOn = 0x0D,
    RecordTVScreen = 0x0F,
    GiveDeckStatus = 0x1A,
    DeckStatus = 0x1B,
    SetMenuLanguage = 0x32,
    ClearAnalogTimer = 0x33,
    SetAnalogTimer = 0x34,
    TimerStatus = 0x35,
    Standby = 0x36,
    Play = 0x41,
    DeckControl = 0x42,
    TimerClearedStatus = 0x43,
    UserControlPressed = 0x44,
    UserControlReleased = 0x45,
    GiveOSDName = 0x46,
    SetOSDName = 0x47,
    SetOSDString = 0x64,
    SetTimerProgramTitle = 0x67,
    SystemAudioModeRequest = 0x70,
    GiveAudioStatus = 0x71,
    SetSystemAudioMode = 0x72,
    ReportAudioStatus = 0x7A,
    GiveSystemAudioModeStatus = 0x7D,
    SystemAudioModeStatus = 0x7E,
    RoutingChange = 0x80,
    RoutingInformation = 0x81,
    ActiveSource = 0x82,
    GivePhysicalAddress = 0x83,
    ReportPhysicalAddress = 0x84,
    RequestActiveSource = 0x85,
    SetStreamPath = 0x86,
    DeviceVendorID = 0x87,
    VendorCommand = 0x89,
    VendorRemoteButtonDown = 0x8A,
    VendorRemoteButtonUp = 0x8B,
    GiveDeviceVendorID = 0x8C,
    MenuRequest = 0x8D,
    MenuStatus = 0x8E,
    GiveDevicePowerStatus = 0x8F,
    ReportPowerStatus = 0x90,
    GetMenuLanguage = 0x91,
    SelectAnalogService = 0x92,
    SelectDigitalService = 0x93,
    SetDigitalTimer = 0x97,
    ClearDigitalTimer = 0x99,
    SetAudioRate = 0x9A,
    InactiveSource = 0x9D,
    CECVersion = 0x9E,
    GetCECVersion = 0x9F,
    VendorCommandWithID = 0xA0,
    ClearExternalTimer = 0xA1,
    SetExternalTimer = 0xA2,
    ReportShortAudioDescriptor = 0xA3,
    RequestShortAudioDescriptor = 0xA4,
    InitARC = 0xC0,
    ReportARCInited = 0xC1,
    ReportARCTerminated = 0xC2,
    RequestARCInit = 0xC3,
    RequestARCTermination = 0xC4,
    TerminateARC = 0xC5,
    CDC = 0xF8,
    Abort = 0xFF,
}

#[repr(i8)]
#[derive(Copy, Clone, Debug, PartialEq, TryFromPrimitive)]
pub enum LogicalAddress {
    Unknown = -1,
    TV = 0,
    RecordingDevice1 = 1,
    RecordingDevice2 = 2,
    Tuner1 = 3,
    PlaybackDevice1 = 4,
    AudioSystem = 5,
    Tuner2 = 6,
    Tuner3 = 7,
    PlaybackDevice2 = 8,
    RecordingDevice3 = 9,
    Tuner4 = 10,
    PlaybackDevice3 = 11,
    Reserved1 = 12,
    Reserved2 = 13,
    FreeUse = 14,
    Broadcast = 15,
}

#[repr(i8)]
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum DeviceTypes {
    TV = 0,
    RecordingDevice = 1,
    Reserved = 2,
    Tuner = 3,
    PlaybackDevice = 4,
    AudioSystem = 5,
    Switch = 6,
    VideoProcessor = 7,
}

#[repr(u8)]
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum UserControl {
    Select = 0x00,
    Up = 0x01,
    Down = 0x02,
    Left = 0x03,
    Right = 0x04,
    RightUp = 0x05,
    RightDown = 0x06,
    LeftUp = 0x07,
    LeftDown = 0x08,
    RootMenu = 0x09,
    SetupMenu = 0x0A,
    ContentsMenu = 0x0B,
    FavoriteMenu = 0x0C,
    Exit = 0x0D,
    Number0 = 0x20,
    Number1 = 0x21,
    Number2 = 0x22,
    Number3 = 0x23,
    Number4 = 0x24,
    Number5 = 0x25,
    Number6 = 0x26,
    Number7 = 0x27,
    Number8 = 0x28,
    Number9 = 0x29,
    Dot = 0x2A,
    Enter = 0x2B,
    Clear = 0x2C,
    ChannelUp = 0x30,
    ChannelDown = 0x31,
    PreviousChannel = 0x32,
    SoundSelect = 0x33,
    InputSelect = 0x34,
    DisplayInformation = 0x35,
    Help = 0x36,
    PageUp = 0x37,
    PageDown = 0x38,
    Power = 0x40,
    VolumeUp = 0x41,
    VolumeDown = 0x42,
    Mute = 0x43,
    Play = 0x44,
    Stop = 0x45,
    Pause = 0x46,
    Record = 0x47,
    Rewind = 0x48,
    FastForward = 0x49,
    Eject = 0x4A,
    Forward = 0x4B,
    Backward = 0x4C,
    Angle = 0x50,
    Subpicture = 0x51,
    VideoOnDemand = 0x52,
    EPG = 0x53,
    TimerProgramming = 0x54,
    InitialConfig = 0x55,
    PlayFunction = 0x60,
    PausePlayFunction = 0x61,
    RecordFunction = 0x62,
    PauseRecordFunction = 0x63,
    StopFunction = 0x64,
    MuteFunction = 0x65,
    RestoreVolumeFunction = 0x66,
    TuneFunction = 0x67,
    SelectDiskFunction = 0x68,
    SelectAVInputFunction = 0x69,
    SelectAudioInputFunction = 0x6A,
    F1Blue = 0x71,
    F2Red = 0x72,
    F3Green = 0x73,
    F4Yellow = 0x74,
    F5 = 0x75,
}
