[package]
name = "cecvol"
version = "0.1.0"
authors = ["Steven Rhodes <rhodes.steven@gmail.com>"]
license = "MIT"
readme = "README.md"
description = "Allow external control of CEC commands to TV"
edition = "2018"

[dependencies]
actix = "0.10"
actix-web = "3.1"
actix-http="2.0"
anyhow = "1.0"
log = "0.4"
cec-rs = "2.0"
libcec-sys = "*"
lazy_static = "1.4"
libc = "0.2"
nix = "0.18"
serde = { version = "1.0", features = ["derive"] } 
env_logger = "0.7"
termion = "1.5"
thiserror = "1.0"

[package.metadata.deb]
maintainer-scripts = "debian/"
systemd-units = { }
